# Generated by Django 2.1.5 on 2019-01-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='text',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
